"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language =
  | 'English' | 'Hindi' | 'Tamil' | 'Telugu' | 'Marathi'
  | 'Bengali' | 'Odia' | 'Kannada' | 'Malayalam' | 'Bodo'
  | 'Dogri' | 'Gujarati' | 'Kashmiri' | 'Konkani' | 'Maithili'
  | 'Manipuri' | 'Nepali' | 'Punjabi' | 'Urdu' | 'Assamese';

export interface LanguageOption {
  code: Language;
  name: string;
}

export const languages: LanguageOption[] = [
  { code: 'English', name: 'English' },
  { code: 'Hindi', name: 'हिंदी (Hindi)' },
  { code: 'Tamil', name: 'தமிழ் (Tamil)' },
  { code: 'Telugu', name: 'తెలుగు (Telugu)' },
  { code: 'Marathi', name: 'मराठी (Marathi)' },
  { code: 'Bengali', name: 'বাংলা (Bengali)' },
  { code: 'Odia', name: 'ଓଡ଼ିଆ (Odia)' },
  { code: 'Kannada', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'Malayalam', name: 'മലയാളം (Malayalam)' },
  { code: 'Bodo', name: 'बर\' (Bodo)' },
  { code: 'Dogri', name: 'डोगरी (Dogri)' },
  { code: 'Gujarati', name: 'ગુજરાતી (Gujarati)' },
  { code: 'Kashmiri', name: 'कॉशुर (Kashmiri)' },
  { code: 'Konkani', name: 'कोंकणी (Konkani)' },
  { code: 'Maithili', name: 'मैथिली (Maithili)' },
  { code: 'Manipuri', name: 'মণিপুরী (Manipuri)' },
  { code: 'Nepali', name: 'नेपाली (Nepali)' },
  { code: 'Punjabi', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'Urdu', name: 'اردو (Urdu)' },
  { code: 'Assamese', name: 'অসমীয়া (Assamese)' },
];

const translations: Record<Language, Record<string, string>> = {
  English: {
    app_title: 'KAAMMADAT',
    powered_by: 'Powered by Team Originn',
    welcome: 'Welcome to Kaammadat',
    subtitle: 'Connecting the workforce of India.',
    i_am_worker: 'I am a Worker',
    i_am_giver: 'I am a Job Giver',
    admin_login: 'Admin Login',
    full_name: 'Full Name',
    mobile_number: 'Mobile Number',
    aadhar_number: 'Aadhar Number',
    address: 'Address',
    email_id: 'Email ID',
    get_otp: 'Get OTP',
    verify_otp: 'Verify OTP',
    enter_otp_sent_to: 'Enter the OTP sent to',
    through: 'through',
    verify_and_login: 'Verify & Login',
    login_success: 'Login Successful!',
    redirecting: 'Redirecting to your dashboard...',
    applied_jobs: 'My Applied Jobs',
    posted_jobs: 'My Posted Works',
    post_new_job: 'Post a New Job',
    search_jobs: 'Search Jobs',
    loyalty_card: 'Workforce Loyalty Card',
    jobs_in_india: 'Jobs All Over India',
    salary: 'Daily Salary',
    location: 'Location',
    slots: 'Slots',
    apply_now: 'Apply Now',
    applied: 'Applied',
    view_apply: 'View & Apply',
    cancel: 'Cancel',
    agree_terms: 'I agree to the Terms & Conditions and confirm that all details provided are unique and true.',
    work_location: 'Work Location Map',
    route_details: 'Route & Distance',
    report_fraud: 'Report Fraud / Fake Job',
    checkout: 'Checkout / Confirm Application',
    upload_images: 'Upload Location Images',
    daily_wages: 'Daily Wages',
    distance: 'Distance',
    duration: 'Duration',
    admin_dashboard: 'Admin Dashboard',
    part_time_jobs: 'Part Time Jobs',
    apply_as_worker: 'Apply as Worker',
    post_part_time_job: 'Post Part Time Job',
    for_students_labourers: 'For Students & Labourers',
  },
  Hindi: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन द्वारा संचालित',
    welcome: 'काममदत में आपका स्वागत है',
    subtitle: 'भारत के कार्यबल को जोड़ना।',
    i_am_worker: 'मैं एक श्रमिक हूँ',
    i_am_giver: 'मैं एक नियोक्ता हूँ',
    admin_login: 'एडमिन लॉगिन',
    full_name: 'पूरा नाम',
    mobile_number: 'मोबाइल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'पता',
    email_id: 'ईमेल आईडी',
    get_otp: 'ओटीपी प्राप्त करें',
    verify_otp: 'ओटीपी सत्यापित करें',
    enter_otp_sent_to: 'भेजा गया ओटीपी दर्ज करें',
    through: 'के माध्यम से',
    verify_and_login: 'सत्यापित करें और लॉगिन करें',
    login_success: 'लॉगिन सफल रहा!',
    redirecting: 'आपके डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है...',
    applied_jobs: 'मेरे लागू किए गए कार्य',
    posted_jobs: 'मेरे पोस्ट किए गए कार्य',
    post_new_job: 'एक नया कार्य पोस्ट करें',
    search_jobs: 'कार्य खोजें',
    loyalty_card: 'कार्यबल वफादारी कार्ड',
    jobs_in_india: 'पूरे भारत में नौकरियां',
    salary: 'दैनिक वेतन',
    location: 'स्थान',
    slots: 'रिक्तियां',
    apply_now: 'अभी लागू करें',
    applied: 'लागू किया गया',
    view_apply: 'देखें और लागू करें',
    cancel: 'रद्द करें',
    agree_terms: 'मैं नियमों और शर्तों से सहमत हूँ और पुष्टि करता हूँ कि प्रदान किए गए सभी विवरण अद्वितीय और सत्य हैं।',
    work_location: 'कार्य स्थान मानचित्र',
    route_details: 'मार्ग और दूरी',
    report_fraud: 'धोखाधड़ी / फर्जी कार्य की रिपोर्ट करें',
    checkout: 'चेकआउट / आवेदन की पुष्टि करें',
    upload_images: 'स्थान के चित्र अपलोड करें',
    daily_wages: 'दैनिक मजदूरी',
    distance: 'दूरी',
    duration: 'समय',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    part_time_jobs: 'अंशकालिक नौकरियां',
    apply_as_worker: 'कर्मचारी के रूप में आवेदन करें',
    post_part_time_job: 'अंशकालिक काम पोस्ट करें',
    for_students_labourers: 'छात्रों और मजदूरों के लिए',
  },
  Tamil: {
    app_title: 'காம்மதத்',
    powered_by: 'டீம் ஒரிஜின் வழங்கும்',
    welcome: 'காம்மதத்திற்கு உங்களை வரவேற்கிறோம்',
    subtitle: 'இந்தியாவின் தொழிலாளர்களை இணைக்கிறது.',
    i_am_worker: 'நான் ஒரு தொழிலாளி',
    i_am_giver: 'நான் ஒரு வேலை வழங்குபவர்',
    admin_login: 'நிர்வாகி உள்நுழைவு',
    full_name: 'முழு பெயர்',
    mobile_number: 'கைபேசி எண்',
    aadhar_number: 'ஆதார் எண்',
    address: 'முகவரி',
    email_id: 'மின்னஞ்சல் முகவரி',
    get_otp: 'ஒடிபி பெறுங்கள்',
    verify_otp: 'ஒடிபி சரிபார்க்கவும்',
    enter_otp_sent_to: 'அனுப்பப்பட்ட ஒடிபியை உள்ளிடவும்',
    through: 'வழியாக',
    verify_and_login: 'சரிபார்த்து உள்நுழைக',
    login_success: 'உள்நுழைவு வெற்றிகரமாக முடிந்தது!',
    redirecting: 'உங்கள் டாஷ்போர்டிற்கு திருப்பி விடப்படுகிறது...',
    applied_jobs: 'விண்ணப்பித்த வேலைகள்',
    posted_jobs: 'பதிவிட்ட வேலைகள்',
    post_new_job: 'புதிய வேலை பதிவிடுக',
    search_jobs: 'வேலை தேடுக',
    loyalty_card: 'தொழிலாளர் விசுவாச அட்டை',
    jobs_in_india: 'இந்தியா முழுவதும் வேலைகள்',
    salary: 'தினசரி சம்பளம்',
    location: 'இடம்',
    slots: 'இடங்கள்',
    apply_now: 'இப்போதே விண்ணப்பிக்கவும்',
    applied: 'விண்ணப்பிக்கப்பட்டது',
    view_apply: 'பார்த்து விண்ணப்பிக்கவும்',
    cancel: 'ரத்து செய்',
    agree_terms: 'விதிமுறைகள் மற்றும் நிபந்தனைகளை நான் ஒப்புக்கொள்கிறேன், வழங்கப்பட்ட விவரங்கள் உண்மையானவை என உறுதிப்படுத்துகிறேன்.',
    work_location: 'வேலை செய்யும் இட வரைபடம்',
    route_details: 'பாதை மற்றும் தூரம்',
    report_fraud: 'மோசடி / போலி வேலை புகார்',
    checkout: 'பரிசீலனை / விண்ணப்ப உறுதிப்படுத்தல்',
    upload_images: 'இடத்தின் படங்களை பதிவேற்றவும்',
    daily_wages: 'தினசரி கூலி',
    distance: 'தூரம்',
    duration: 'கால அளவு',
    admin_dashboard: 'நிர்வாக டாஷ்போர்டு',
    part_time_jobs: 'பகுதி நேர வேலைகள்',
    apply_as_worker: 'தொழிலாளராக விண்ணப்பிக்கவும்',
    post_part_time_job: 'பகுதி நேர வேலையை பதிவிடுக',
    for_students_labourers: 'மாணவர்கள் மற்றும் கூலி ஆட்களுக்கு',
  },
  Telugu: {
    app_title: 'కామదత్',
    powered_by: 'టీమ్ ఒరిజిన్ ద్వారా శక్తివంతం',
    welcome: 'కామదత్ కు స్వాగతం',
    subtitle: 'భారతదేశ శ్రామిక శక్తిని అనుసంధానించడం.',
    i_am_worker: 'నేను ఒక కార్మికుడిని',
    i_am_giver: 'నేను ఒక యజమానిని',
    admin_login: 'అడ్మిన్ లాగిన్',
    full_name: 'పూర్తి పేరు',
    mobile_number: 'మొబైల్ సంఖ్య',
    aadhar_number: 'ఆధార్ సంఖ్య',
    address: 'చిరునామా',
    email_id: 'ఇమెయిల్ ఐడి',
    get_otp: 'ఓటీపీ పొందండి',
    verify_otp: 'ఓటీపీని ధృవీకరించండి',
    enter_otp_sent_to: 'పంపిన ఓటీపీని నమోదు చేయండి',
    through: 'ద్వారా',
    verify_and_login: 'ధృవీకరించి లాగిన్ అవ్వండి',
    login_success: 'లాగిన్ విజయవంతమైంది!',
    redirecting: 'మీ డాష్‌బోర్డ్‌కు దారి మళ్లిస్తున్నాము...',
    applied_jobs: 'నా దరఖాస్తులు',
    posted_jobs: 'నా పోస్ట్‌లు',
    post_new_job: 'కొత్త పనిని పోస్ట్ చేయండి',
    search_jobs: 'పనుల కొరకు శోధించండి',
    loyalty_card: 'లాయల్టీ కార్డ్',
    jobs_in_india: 'భారతదేశమంతటా పనులు',
    salary: 'రోజువారీ జీతం',
    location: 'ప్రాంతం',
    slots: 'ఖాళీలు',
    apply_now: 'ఇప్పుడే దరఖాస్తు చేసుకోండి',
    applied: 'దరఖాస్తు చేయబడింది',
    view_apply: 'చూసి దరఖాస్తు చేయండి',
    cancel: 'రద్దు చేయి',
    agree_terms: 'నేను నిబంధనలు మరియు షరతులకు అంగీకరిస్తున్నాను మరియు నా వివరాలు నిజమని ధృవీకరిస్తున్నాను.',
    work_location: 'పని ప్రాంత పటం',
    route_details: 'మార్గం & దూరం',
    report_fraud: 'మోసపూరిత పనిపై ఫిర్యాదు',
    checkout: 'చెకౌట్ / దరఖాస్తు నిర్ధారణ',
    upload_images: 'ప్రాంత చిత్రాలను అప్‌లోడ్ చేయండి',
    daily_wages: 'రోజువారీ కూలి',
    distance: 'దూరం',
    duration: 'సమయం',
    admin_dashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    part_time_jobs: 'పార్ట్ టైమ్ ఉద్యోగాలు',
    apply_as_worker: 'కార్మికుడిగా దరఖాస్తు చేయండి',
    post_part_time_job: 'పార్ట్ టైమ్ పని పోస్ట్ చేయండి',
    for_students_labourers: 'విద్యార్థులు మరియు కూలీలకు',
  },
  Marathi: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन द्वारे संचालित',
    welcome: 'काममदत मध्ये आपले स्वागत आहे',
    subtitle: 'भारतातील कार्यबलाला जोडत आहे.',
    i_am_worker: 'मी एक कामगार आहे',
    i_am_giver: 'मी एक नियोक्ता आहे',
    admin_login: 'अॅडमिन लॉगिन',
    full_name: 'पूर्ण नाव',
    mobile_number: 'मोबाईल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'पत्ता',
    email_id: 'ईमेल आयडी',
    get_otp: 'ओटीपी मिळवा',
    verify_otp: 'ओटीपी सत्यापित करा',
    enter_otp_sent_to: 'पाठवलेला ओटीपी प्रविष्ट करा',
    through: 'च्या माध्यमातून',
    verify_and_login: 'सत्यापित करा आणि लॉगिन करा',
    login_success: 'लॉगिन यशस्वी झाले!',
    redirecting: 'आपल्या डॅशबोर्डवर नेले जात आहे...',
    applied_jobs: 'माझे अर्ज केलेले काम',
    posted_jobs: 'माझे पोस्ट केलेले काम',
    post_new_job: 'नवीन काम पोस्ट करा',
    search_jobs: 'कामे शोधा',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'संपूर्ण भारतात नोकऱ्या',
    salary: 'दैनिक वेतन',
    location: 'स्थान',
    slots: 'जागा',
    apply_now: 'आता अर्ज करा',
    applied: 'अर्ज केला',
    view_apply: 'पहा आणि अर्ज करा',
    cancel: 'रद्द करा',
    agree_terms: 'मी अटी व शर्तींशी सहमत आहे आणि प्रदान केलेली माहिती खरी असल्याचे घोषित करतो.',
    work_location: 'कामाचे ठिकाण नकाशा',
    route_details: 'मार्ग आणि अंतर',
    report_fraud: 'फसव्या कामाची तक्रार करा',
    checkout: 'चेकआउट / अर्जाची पुष्टी करा',
    upload_images: 'कामाच्या जागेचे फोटो अपलोड करा',
    daily_wages: 'दैनिक मजुरी',
    distance: 'अंतर',
    duration: 'वेळ',
    admin_dashboard: 'अॅडमिन डॅशबोर्ड',
    part_time_jobs: 'अर्धवेळ नोकऱ्या',
    apply_as_worker: 'कामगार म्हणून अर्ज करा',
    post_part_time_job: 'अर्धवेळ काम पोस्ट करा',
    for_students_labourers: 'विद्यार्थी आणि मजुरांसाठी',
  },
  Bengali: {
    app_title: 'কামমদত',
    powered_by: 'টিম অরিজিন দ্বারা চালিত',
    welcome: 'কামমদত-এ আপনাকে স্বাগত',
    subtitle: 'ভারতের শ্রমশক্তিকে সংযুক্ত করা হচ্ছে।',
    i_am_worker: 'আমি একজন কর্মী',
    i_am_giver: 'আমি একজন নিয়োগকর্তা',
    admin_login: 'অ্যাডমিন লগইন',
    full_name: 'সম্পূর্ণ নাম',
    mobile_number: 'মোবাইল নম্বর',
    aadhar_number: 'আধার নম্বর',
    address: 'ঠিকানা',
    email_id: 'ইমেল আইডি',
    get_otp: 'ওটিপি পান',
    verify_otp: 'ওটিপি যাচাই করুন',
    enter_otp_sent_to: 'প্রেরিত ওটিপি লিখুন',
    through: 'মাধ্যমে',
    verify_and_login: 'যাচাই এবং লগইন করুন',
    login_success: 'লগইন সফল হয়েছে!',
    redirecting: 'আপনার ড্যাশবোর্ডে পাঠানো হচ্ছে...',
    applied_jobs: 'আমার আবেদনসমূহ',
    posted_jobs: 'আমার পোস্টসমূহ',
    post_new_job: 'নতুন কাজ পোস্ট করুন',
    search_jobs: 'কাজ খুঁজুন',
    loyalty_card: 'লয়্যালটি কার্ড',
    jobs_in_india: 'সারা ভারতে কাজ',
    salary: 'দৈনিক বেতন',
    location: 'স্থান',
    slots: 'শূন্যপদ',
    apply_now: 'এখনই আবেদন করুন',
    applied: 'আবেদন করা হয়েছে',
    view_apply: 'দেখুন ও আবেদন করুন',
    cancel: 'বাতিল করুন',
    agree_terms: 'আমি নিয়ম ও শর্তাবলীতে সম্মত এবং প্রদত্ত সমস্ত বিবরণ সত্য বলে নিশ্চিত করছি।',
    work_location: 'কাজের স্থান মানচিত্র',
    route_details: 'পথ ও দূরত্ব',
    report_fraud: 'ভুয়ো কাজের রিপোর্ট করুন',
    checkout: 'চেকআউট / আবেদন নিশ্চিত করুন',
    upload_images: 'কাজের জায়গার ছবি আপলোড করুন',
    daily_wages: 'দৈনিক মজুরি',
    distance: 'দূরত্ব',
    duration: 'সময়',
    admin_dashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    part_time_jobs: 'খণ্ডকালীন কাজ',
    apply_as_worker: 'কর্মী হিসাবে আবেদন করুন',
    post_part_time_job: 'খণ্ডকালীন কাজ পোস্ট করুন',
    for_students_labourers: 'ছাত্র ও শ্রমিকদের জন্য',
  },
  Odia: {
    app_title: 'କାମମଦତ',
    powered_by: 'ଟିମ୍ ଓରିଜିନ ଦ୍ଵାରା ଚାଳିତ',
    welcome: 'କାମମଦତରେ ଆପଣଙ୍କୁ ସ୍ଵାଗତ',
    subtitle: 'ଭାରତର ଶ୍ରମିକମାନଙ୍କୁ ସଂଯୋଗ କରୁଛି।',
    i_am_worker: 'ମୁଁ ଜଣେ ଶ୍ରମିକ',
    i_am_giver: 'ମୁଁ ଜଣେ ନିଯୁକ୍ତିଦାତା',
    admin_login: 'ଆଡମିନ ଲଗଇନ୍',
    full_name: 'ପୂରା ନାମ',
    mobile_number: 'ମୋବାଇଲ୍ ନମ୍ବର',
    aadhar_number: 'ଆଧାର ନମ୍ବର',
    address: 'ଠିକଣା',
    email_id: 'ଇମେଲ୍ ଆଇଡି',
    get_otp: 'ଓଟିପି ପାଆନ୍ତୁ',
    verify_otp: 'ଓଟିପି ଯାଞ୍ଚ କରନ୍ତୁ',
    enter_otp_sent_to: 'ପଠାଯାଇଥିବା ଓଟିପି ପ୍ରବେଶ କରନ୍ତୁ',
    through: 'ମାଧ୍ୟମରେ',
    verify_and_login: 'ଯାଞ୍ଚ ଏବଂ ଲଗଇନ୍',
    login_success: 'ଲଗଇନ୍ ସଫଳ ହେଲା!',
    redirecting: 'ଆପଣଙ୍କ ଡ୍ୟାସବୋର୍ଡକୁ ପଠାଯାଉଛି...',
    applied_jobs: 'ମୋର ଆବେଦିତ କାର୍ଯ୍ୟ',
    posted_jobs: 'ମୋର ପୋଷ୍ଟ ହୋଇଥିବା କାର୍ଯ୍ୟ',
    post_new_job: 'ନୂଆ କାର୍ଯ୍ୟ ପୋଷ୍ଟ କରନ୍ତୁ',
    search_jobs: 'କାର୍ଯ୍ୟ ଖୋଜନ୍ତୁ',
    loyalty_card: 'ଲୟାଲଟି କାର୍ଡ',
    jobs_in_india: 'ସାରା ଭାରତରେ ଚାକିରି',
    salary: 'ଦୈନିକ ଦରମା',
    location: 'ସ୍ଥାନ',
    slots: 'ଖାଲି ସ୍ଥାନ',
    apply_now: 'ଏବେ ଆବେଦନ କରନ୍ତୁ',
    applied: 'ଆବେଦନ ହୋଇଛି',
    view_apply: 'ଦେଖନ୍ତୁ ଏବଂ ଆବେଦନ କରନ୍ତୁ',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    agree_terms: 'ମୁଁ ସର୍ତ୍ତାବଳୀରେ ସହମତ ଏବଂ ପ୍ରଦତ୍ତ ସମସ୍ତ ବିବରଣୀ ସତ୍ୟ ବୋଲି ନିଶ୍ଚିତ କରୁଛି।',
    work_location: 'କାର୍ଯ୍ୟ ସ୍ଥାନ ମାନଚିତ୍ର',
    route_details: 'ମାର୍ଗ ଓ ଦୂରତା',
    report_fraud: 'ଜାଲ୍ କାର୍ଯ୍ୟର ରିପୋର୍ଟ କରନ୍ତୁ',
    checkout: 'ଚେକଆଉଟ୍ / ଆବେଦନ ନିଶ୍ଚିତ କରନ୍ତୁ',
    upload_images: 'ସ୍ଥାନର ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ',
    daily_wages: 'ଦୈନିକ ମଜୁରି',
    distance: 'ଦୂରତା',
    duration: 'ସମୟ',
    admin_dashboard: 'ଆଡମିନ ଡ୍ୟାସବୋର୍ଡ',
    part_time_jobs: 'ଅଂଶ ସମୟ କାର୍ଯ୍ୟ',
    apply_as_worker: 'କର୍ମଚାରୀ ଭାବେ ଆବେଦନ',
    post_part_time_job: 'ଅଂଶ ସମୟ କାର୍ଯ୍ୟ ପୋଷ୍ଟ',
    for_students_labourers: 'ଛାତ୍ର ଓ ଶ୍ରମିକଙ୍କ ପାଇଁ',
  },
  Kannada: {
    app_title: 'ಕಾಮಮದತ್',
    powered_by: 'ಟೀಮ್ ಒರಿಜಿನ್ ನಡೆಸುವ',
    welcome: 'ಕಾಮಮದತ್ ಗೆ ಸುಸ್ವಾಗತ',
    subtitle: 'ಭಾರತದ ಶ್ರಮಿಕ ವರ್ಗವನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ.',
    i_am_worker: 'ನಾನು ಒಬ್ಬ ಕೆಲಸಗಾರ',
    i_am_giver: 'ನಾನು ಒಬ್ಬ ಉದ್ಯೋಗದಾತ',
    admin_login: 'ಅಡ್ಮಿನ್ ಲಾಗಿನ್',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    mobile_number: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    aadhar_number: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
    address: 'ವಿಳಾಸ',
    email_id: 'ಇಮೇಲ್ ಐಡಿ',
    get_otp: 'ಒಟಿಪಿ ಪಡೆಯಿರಿ',
    verify_otp: 'ಒಟಿಪಿ ಪರಿಶೀಲಿಸಿ',
    enter_otp_sent_to: 'ಕಳುಹಿಸಲಾದ ಒಟಿಪಿಯನ್ನು ನಮೂದಿಸಿ',
    through: 'ಮೂಲಕ',
    verify_and_login: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗ್ ಇನ್ ಮಾಡಿ',
    login_success: 'ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    redirecting: 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ...',
    applied_jobs: 'ನಾನು ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ಕೆಲಸಗಳು',
    posted_jobs: 'ನಾನು ಹಾಕಿರುವ ಕೆಲಸಗಳು',
    post_new_job: 'ಹೊಸ ಕೆಲಸವನ್ನು ಹಾಕಿ',
    search_jobs: 'ಕೆಲಸ ಹುಡುಕಿ',
    loyalty_card: 'ಲಾಯಲ್ಟಿ ಕಾರ್ಡ್',
    jobs_in_india: 'ಭಾರತದಾದ್ಯಂತ ಕೆಲಸಗಳು',
    salary: 'ದೈನಂದಿನ ಸಂಬಳ',
    location: 'ಸ್ಥಳ',
    slots: 'ಸ್ಥಾನಗಳು',
    apply_now: 'ಈಗಲೇ ಅರ್ಜಿ ಹಾಕಿ',
    applied: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    view_apply: 'ನೋಡಿ ಮತ್ತು ಅರ್ಜಿ ಹಾಕಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    agree_terms: 'ನಾನು ನಿಯಮ ಮತ್ತು ನಿಬಂಧನೆಗಳಿಗೆ ಒಪ್ಪುತ್ತೇನೆ ಮತ್ತು ಎಲ್ಲಾ ವಿವರಗಳು ನಿಜವೆಂದು ಖಚಿತಪಡಿಸುತ್ತೇನೆ.',
    work_location: 'ಕೆಲಸದ ಸ್ಥಳದ ನಕ್ಷೆ',
    route_details: 'ಮಾರ್ಗ ಮತ್ತು ದೂರ',
    report_fraud: 'ವಂಚನೆ ಕೆಲಸದ ಬಗ್ಗೆ ವರದಿ ಮಾಡಿ',
    checkout: 'ಚೆಕೌಟ್ / ಅರ್ಜಿಯನ್ನು ಖಚಿತಪಡಿಸಿ',
    upload_images: 'ಸ್ಥಳದ ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    daily_wages: 'ದೈನಂದಿನ ಕೂಲಿ',
    distance: 'ದೂರ',
    duration: 'ಸಮಯ',
    admin_dashboard: 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    part_time_jobs: 'ಅರೆಕಾಲಿಕ ಉದ್ಯೋಗಗಳು',
    apply_as_worker: 'ಕೆಲಸಗಾರನಾಗಿ ಅರ್ಜಿ ಹಾಕಿ',
    post_part_time_job: 'ಅರೆಕಾಲಿಕ ಕೆಲಸ ಹಾಕಿ',
    for_students_labourers: 'ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಕೂಲಿಗಳಿಗೆ',
  },
  Malayalam: {
    app_title: 'കാമമദത്',
    powered_by: 'ടീം ഒറിജിൻ പിന്തുണയോടെ',
    welcome: 'കാമമദതിലേക്ക് സ്വാഗതം',
    subtitle: 'ഇന്ത്യയിലെ തൊഴിലാളികളെ ബന്ധിപ്പിക്കുന്നു.',
    i_am_worker: 'ഞാൻ ഒരു തൊഴിലാളിയാണ്',
    i_am_giver: 'ഞാൻ ഒരു തൊഴിൽദാതാവാണ്',
    admin_login: 'അഡ്മിൻ ലോഗിൻ',
    full_name: 'പൂർണ്ണ നാമം',
    mobile_number: 'മൊബൈൽ നമ്പർ',
    aadhar_number: 'ആധാർ നമ്പർ',
    address: 'മേൽവിലാസം',
    email_id: 'ഇമെയിൽ ഐഡി',
    get_otp: 'ഒടിപി നേടുക',
    verify_otp: 'ഒടിപി പരിശോധിക്കുക',
    enter_otp_sent_to: 'ലഭിച്ച ഒടിപി നൽകുക',
    through: 'വഴി',
    verify_and_login: 'പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക',
    login_success: 'ലോഗിൻ വിജയകരമായി!',
    redirecting: 'നിങ്ങളുടെ ഡാഷ്‌ബോർഡിലേക്ക് പോകുന്നു...',
    applied_jobs: 'അപേക്ഷിച്ച ജോലികൾ',
    posted_jobs: 'പോസ്റ്റ് ചെയ്ത ജോലികൾ',
    post_new_job: 'പുതിയ ജോലി പോസ്റ്റ് ചെയ്യുക',
    search_jobs: 'ജോലി തിരയുക',
    loyalty_card: 'ലോയൽറ്റി കാർഡ്',
    jobs_in_india: 'ഇന്ത്യയിലുടനീളം ജോലികൾ',
    salary: 'ദിനക്കൂലി',
    location: 'സ്ഥലം',
    slots: 'ഒഴിവുകൾ',
    apply_now: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    applied: 'അപേക്ഷിച്ചു',
    view_apply: 'നോക്കി അപേക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    agree_terms: 'ഞാൻ നിബന്ധനകളും വ്യവസ്ഥകളും അംഗീകരിക്കുന്നു, വിവരങ്ങൾ സത്യമാണെന്ന് ഉറപ്പ് നൽകുന്നു.',
    work_location: 'തൊഴിൽ സ്ഥലത്തിന്റെ മാപ്പ്',
    route_details: 'വഴിയും ദൂരവും',
    report_fraud: 'വ്യാജ ജോലിയെക്കുറിച്ച് പരാതിപ്പെടുക',
    checkout: 'ചെക്ക്ഔട്ട് / അപേക്ഷ ഉറപ്പാക്കുക',
    upload_images: 'സ്ഥലത്തിന്റെ ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക',
    daily_wages: 'ദിനക്കൂലി',
    distance: 'ദൂരം',
    duration: 'സമയം',
    admin_dashboard: 'അഡ്മിൻ ഡാഷ്‌ബോർഡ്',
    part_time_jobs: 'പാർട്ട് ടൈം ജോലികൾ',
    apply_as_worker: 'തൊഴിലാളിയായി അപേക്ഷിക്കുക',
    post_part_time_job: 'പാർട്ട് ടൈം ജോലി പോസ്റ്റ് ചെയ്യുക',
    for_students_labourers: 'വിദ്യാർഥികൾക്കും തൊഴിലാളികൾക്കും',
  },
  Bodo: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन दैदेनाय',
    welcome: 'काममदताव बरायबाय',
    subtitle: 'भारतनि मावथि हान्जाफोरखौ फोनांजाबनाय।',
    i_am_worker: 'आं सासे मावथि',
    i_am_giver: 'आं सासे खामानि होनाय',
    admin_login: 'एडमिन लॉगिन',
    full_name: 'मुं आबुं',
    mobile_number: 'मोबाइल अनजिमा',
    aadhar_number: 'आधार अनजिमा',
    address: 'ठिकाना',
    email_id: 'इमेल आइदि',
    get_otp: 'ओटिपि लों',
    verify_otp: 'ओटिपि आनजाद खालाम',
    enter_otp_sent_to: 'हरनाय ओटिपिखौ टाइप खालाम',
    through: 'गेजेरजों',
    verify_and_login: 'आनजाद खालामना हाब',
    login_success: 'हाबनाया जाफुंबाय!',
    redirecting: 'डैशबोर्डआव थांगासिनो दं...',
    applied_jobs: 'आं आबेदन खालामनाय खामानि',
    posted_jobs: 'आं होनाय खामानिफोर',
    post_new_job: 'गोदान खामानि फोसाव',
    search_jobs: 'खामानि नागिर',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'गाबराव भारतनि खामानिफोर',
    salary: 'सानफ्रामनि हाजिरा',
    location: 'जायगा',
    slots: 'जायगाफोर',
    apply_now: 'दा आबेदन खालाम',
    applied: 'आबेदन खालामबाय',
    view_apply: 'नायना आबेदन खालाम',
    cancel: 'रद खालाम',
    agree_terms: 'आं रादिखौ मानियो आरो होनाय बाथ्राफोरखौ सैथो होनना थिरां खालामो।',
    work_location: 'खामानि जायगानि मानचित्र',
    route_details: 'लामा आरो जानथाय',
    report_fraud: 'नंखाय खामानि रिपोर्ट खालाम',
    checkout: 'आबेदनखौ थिरां खालाम',
    upload_images: 'जायगानि सावगारि अपलोड खालाम',
    daily_wages: 'सानफ्रामनि हाजिरा',
    distance: 'जानथाय',
    duration: 'सम',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    part_time_jobs: 'पार्ट टाइम काम',
    apply_as_worker: 'मावथि हिसेबे आबेदन',
    post_part_time_job: 'पार्ट टाइम काम फोसाव',
    for_students_labourers: 'छात्र आरो मावथिफोरनि थाखाय',
  },
  Dogri: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन आह्ले',
    welcome: 'काममदता च स्वागत ऐ',
    subtitle: 'भारत दे कामगारें गी जोड़ना।',
    i_am_worker: 'मूं इक मजदूर हां',
    i_am_giver: 'मूं इक नौकरी देने आह्ला हां',
    admin_login: 'एडमिन लागिन',
    full_name: 'पूरा नां',
    mobile_number: 'मोबाइल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'पता',
    email_id: 'ईमेल आईडी',
    get_otp: 'ओटीपी हासल करो',
    verify_otp: 'ओटीपी परखो',
    enter_otp_sent_to: 'भेजे दा ओटीपी पाओ',
    through: 'दे राहें',
    verify_and_login: 'परखी यै लागिन करो',
    login_success: 'लागिन सफल होया!',
    redirecting: 'डैशबोर्ड पर लै जा करदे हां...',
    applied_jobs: 'मेरे अप्लाइ कीते दे काम',
    posted_jobs: 'मेरे पाए दे काम',
    post_new_job: 'नमां काम पाओ',
    search_jobs: 'काम लब्भो',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'सारे भारत च नौकरियां',
    salary: 'दिहाड़ी',
    location: 'थाहर',
    slots: 'खाली थान',
    apply_now: 'हुण अप्लाइ करो',
    applied: 'अप्लाइ कीता',
    view_apply: 'दिक्खो ते अप्लाइ करो',
    cancel: 'रद्द करो',
    agree_terms: 'मूं शर्ते कन्नै सहमत हां ते दीती दी जानकारी सच ऐ।',
    work_location: 'काम दे थाहर दा नक्शा',
    route_details: 'राह ते दूरी',
    report_fraud: 'फर्जी काम दी रिपोर्ट करो',
    checkout: 'अप्लाई पक्का करो',
    upload_images: 'थाहर दी फोटो अपलोड करो',
    daily_wages: 'दिहाड़ी मजदूरी',
    distance: 'दूरी',
    duration: 'वक्त',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    part_time_jobs: 'पार्ट टाइम काम',
    apply_as_worker: 'मजदूर वजों अप्लाई करो',
    post_part_time_job: 'पार्ट टाइम काम पाओ',
    for_students_labourers: 'छात्रें ते मजदूरें लई',
  },
  Gujarati: {
    app_title: 'કામમદત',
    powered_by: 'ટીમ ઓરિજિન દ્વારા સંચાલિત',
    welcome: 'કામમદતમાં આપનું સ્વાગત છે',
    subtitle: 'ભારતના શ્રમિક વર્ગને જોડવું.',
    i_am_worker: 'હું શ્રમિક છું',
    i_am_giver: 'હું નોકરી આપનાર છું',
    admin_login: 'એડમિન લોગિન',
    full_name: 'પૂરું નામ',
    mobile_number: 'મોબાઇલ નંબર',
    aadhar_number: 'આધાર નંબર',
    address: 'સરનામું',
    email_id: 'ઇમેઇલ આઇડી',
    get_otp: 'ઓટીપી મેળવો',
    verify_otp: 'ઓટીપી વેરિફાય કરો',
    enter_otp_sent_to: 'મોકલેલ ઓટીપી દાખલ કરો',
    through: 'દ્વારા',
    verify_and_login: 'વેરિફાય અને લોગિન કરો',
    login_success: 'લોગિન સફળ રહ્યું!',
    redirecting: 'ડેશબોર્ડ પર લઈ જઈ રહ્યા છીએ...',
    applied_jobs: 'મારા અરજી કરેલ કામ',
    posted_jobs: 'મારા પોસ્ટ કરેલ કામ',
    post_new_job: 'નવું કામ પોસ્ટ કરો',
    search_jobs: 'કામ શોધો',
    loyalty_card: 'લોયલ્ટી કાર્ડ',
    jobs_in_india: 'સમગ્ર ભારતમાં નોકરીઓ',
    salary: 'દૈનિક પગાર',
    location: 'સ્થળ',
    slots: 'જગ્યાઓ',
    apply_now: 'હમણાં જ અરજી કરો',
    applied: 'અરજી કરેલ છે',
    view_apply: 'જુઓ અને અરજી કરો',
    cancel: 'રદ કરો',
    agree_terms: 'હું નિયમો અને શરતો સાથે સંમત છું અને ખાતરી આપું છું કે આપેલી વિગતો સાચી છે.',
    work_location: 'કામનું સ્થળ નકશો',
    route_details: 'માર્ગ અને અંતર',
    report_fraud: 'ખોટી નોકરીની જાણ કરો',
    checkout: 'ચેકઆઉટ / અરજીની ખાતરી કરો',
    upload_images: 'સ્થળના ફોટા અપલોડ કરો',
    daily_wages: 'રોજિંદી મજૂરી',
    distance: 'અંતર',
    duration: 'સમય',
    admin_dashboard: 'એડમિન ડેશબોર્ડ',
    part_time_jobs: 'પાર્ટ ટાઇમ નોકરીઓ',
    apply_as_worker: 'કામદાર તરીકે અરજી કરો',
    post_part_time_job: 'પાર્ટ ટાઇમ કામ પોસ્ટ કરો',
    for_students_labourers: 'વિદ્યાર્થીઓ અને મજૂરો માટે',
  },
  Kashmiri: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन ज़रिथ',
    welcome: 'काममदताहस मंज़ खुशामदीद',
    subtitle: 'हिंदुस्तानुक मज़दूर कुन करुन।',
    i_am_worker: 'बह छुस मज़दूर',
    i_am_giver: 'बह छुस काम दिनवोल',
    admin_login: 'एडमिन लागिन',
    full_name: 'पूर नाव',
    mobile_number: 'मोबाइल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'पता',
    email_id: 'ईमेल आईडी',
    get_otp: 'ओटीपी मंगायिव',
    verify_otp: 'ओटीपी जांचिव',
    enter_otp_sent_to: 'सोतमुत ओटीपी दर्ज करिव',
    through: 'ज़रिय',
    verify_and_login: 'जांचिव ते लागिन करिव',
    login_success: 'लागिन कामयाब!',
    redirecting: 'डैशबोर्डस कुन गछान...',
    applied_jobs: 'मय आवेदर कोरमुत काम',
    posted_jobs: 'मय द्युतमुत काम',
    post_new_job: 'नयुव काम दियिव',
    search_jobs: 'काम छांडिव',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'सारे हिंदुस्तानस मंज़ काम',
    salary: 'दोज',
    location: 'जाय',
    slots: 'जायि खाली',
    apply_now: 'वैन्यई एप्लाई करिव',
    applied: 'एप्लाई कोर',
    view_apply: 'विछिव ते एप्लाई करिव',
    cancel: 'रद्द करिव',
    agree_terms: 'बह छुस शर्तेन मानान ते दितमुत माहिती छै पोज़।',
    work_location: 'काम जायि हुंद नक्श',
    route_details: 'वत ते फासल',
    report_fraud: 'धोखेबाज़ कामि हुंद रिपोर्ट करिव',
    checkout: 'एप्लाई पक्क करिव',
    upload_images: 'जायि हुंद फोटो अपलोड करिव',
    daily_wages: 'दोज़ मजूरी',
    distance: 'फासल',
    duration: 'वक़्त',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    part_time_jobs: 'पार्ट टाइम काम',
    apply_as_worker: 'मज़दूर के तौर पर अर्जी दो',
    post_part_time_job: 'पार्ट टाइम काम पोस्ट करो',
    for_students_labourers: 'छात्रों और मजदूरों के लिए',
  },
  Konkani: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन वरवीं',
    welcome: 'काममदतांत येवकार',
    subtitle: 'भारताच्या वावराड्यांक जोडप।',
    i_am_worker: 'हांव एक वावराडी',
    i_am_giver: 'हांव एक काम दिवपी',
    admin_login: 'एडमिन लॉगिन',
    full_name: 'पूर्ण नांव',
    mobile_number: 'मोबाईल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'नामो',
    email_id: 'ईमेल आयडी',
    get_otp: 'ओटीपी मेळयात',
    verify_otp: 'ओटीपी तपासून पळयात',
    enter_otp_sent_to: 'धाडिल्लो ओटीपी घालात',
    through: 'वरवीं',
    verify_and_login: 'तपासून लॉगिन करात',
    login_success: 'लॉगिन जाले!',
    redirecting: 'डॅशबोर्डाचेर व्हेत आसा...',
    applied_jobs: 'हांवे अर्ज केल्लीं कामां',
    posted_jobs: 'हांवे घाल्लीं कामां',
    post_new_job: 'नवे काम घालात',
    search_jobs: 'कामाचा सोद करात',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'सगळ्या भारतांत कामां',
    salary: 'दिसाची मजुरी',
    location: 'सुवात',
    slots: 'जागो',
    apply_now: 'आतांच अर्ज करात',
    applied: 'अर्ज केला',
    view_apply: 'पळयात आनी अर्ज करात',
    cancel: 'रद्द करात',
    agree_terms: 'हांव अटी आनी नियमांक मान्य आसा आनी माहिती खरी आसा म्हण जाहीर करता।',
    work_location: 'कामाचे सुवातेचा नकाशा',
    route_details: 'रस्तो आनी अंतर',
    report_fraud: 'फटकिऱ्या कामाची तक्रार करात',
    checkout: 'अर्ज निश्चीत करात',
    upload_images: 'सुवातेचे फोटो अपलोड करात',
    daily_wages: 'दिसाची मजुरी',
    distance: 'अंतर',
    duration: 'वेळ',
    admin_dashboard: 'एडमिन डॅशबोर्ड',
    part_time_jobs: 'पार्ट टाइम कामां',
    apply_as_worker: 'वावराडी म्हणून अर्ज करात',
    post_part_time_job: 'पार्ट टाइम काम घालात',
    for_students_labourers: 'विद्यार्थी आनी मजुरांसाठी',
  },
  Maithili: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन द्वारा चालित',
    welcome: 'काममदत में अहाँक स्वागत अछि',
    subtitle: 'भारतक कार्यबल केँ जोड़ब।',
    i_am_worker: 'हम एकटा मजदूर छी',
    i_am_giver: 'हम एकटा काम देनिहार छी',
    admin_login: 'एडमिन लॉगिन',
    full_name: 'पूरा नाम',
    mobile_number: 'मोबाइल नंबर',
    aadhar_number: 'आधार नंबर',
    address: 'पता',
    email_id: 'ईमेल आईडी',
    get_otp: 'ओटीपी प्राप्त करू',
    verify_otp: 'ओटीपी सत्यापित करू',
    enter_otp_sent_to: 'पठायल ओटीपी दर्ज करू',
    through: 'के माध्यम से',
    verify_and_login: 'सत्यापित करू आ लॉगिन करू',
    login_success: 'लॉगिन सफल रहल!',
    redirecting: 'अहाँक डैशबोर्ड पर लऽ जा रहल छी...',
    applied_jobs: 'हमर आवेदन कएल काम',
    posted_jobs: 'हमर पोस्ट कएल काम',
    post_new_job: 'नब काम पोस्ट करू',
    search_jobs: 'काम खोजू',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'पूरा भारत में नौकरी',
    salary: 'दैनिक वेतन',
    location: 'स्थान',
    slots: 'खाली स्थान',
    apply_now: 'एखनहि आवेदन करू',
    applied: 'आवेदन कएल गेल',
    view_apply: 'देखू आ आवेदन करू',
    cancel: 'रद्द करू',
    agree_terms: 'हम नियम आ शर्त सँ सहमत छी आ देल गेल जानकारी सत्य अछि।',
    work_location: 'कार्य स्थानक नक्शा',
    route_details: 'मार्ग आ दूरी',
    report_fraud: 'जाली कामक रिपोर्ट करू',
    checkout: 'आवेदन पक्का करू',
    upload_images: 'स्थानक फोटो अपलोड करू',
    daily_wages: 'दैनिक मजुरी',
    distance: 'दूरी',
    duration: 'समय',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    part_time_jobs: 'आंशिक समय काम',
    apply_as_worker: 'मजदूर के रूप में आवेदन करें',
    post_part_time_job: 'आंशिक समय काम पोस्ट करें',
    for_students_labourers: 'छात्र और मजदूरों के लिए',
  },
  Manipuri: {
    app_title: 'কামমদত',
    powered_by: 'টীম ওরিজিনগী মতেংগা লোয়ননা',
    welcome: 'কামমদততা তরাম্না ওকচরি',
    subtitle: 'ভারতকী থবক শুবা কাংলুপপু শম্নহনবা।',
    i_am_worker: 'ঐহাক থবক শুবা মীওই অমনি',
    i_am_giver: 'ঐহাক থবক পীবী মীওই অমনি',
    admin_login: 'এদমিন লোগিন',
    full_name: 'মপুং ফাবা মিং',
    mobile_number: 'মোবাইল নম্বর',
    aadhar_number: 'আধার নম্বর',
    address: 'লৈফম ঠিকানা',
    email_id: 'ইমেল আইডি',
    get_otp: 'ওটিপি লৌখতউ',
    verify_otp: 'ওটিপি লেংথকউ',
    enter_otp_sent_to: 'থারকপা ওটিপি নমউ',
    through: 'উথংদা',
    verify_and_login: 'চেক তৌদুনা লোগিন তৌ',
    login_success: 'লোগিন মাইপাক্লে!',
    redirecting: 'ড্যাশবোর্তা চৎখিগদৌরি...',
    applied_jobs: 'ঐহাক্না দরখাস্ত তৌখিবা থবক',
    posted_jobs: 'ঐহাক্না পীখিবা থবক',
    post_new_job: 'অনৌবা থবক থাগৎউ',
    search_jobs: 'থবক থীউ',
    loyalty_card: 'লোয়লটি কার্দ',
    jobs_in_india: 'ভারত শিনবা থুংনা লৈবা থবক',
    salary: 'নুমিত খুদিংগী তনখা',
    location: 'মফম',
    slots: 'অহেনবা মফম',
    apply_now: 'হৌজিক দরখাস্ত তৌ',
    applied: 'দরখাস্ত তৌখ্রে',
    view_apply: 'য়েংউ লোয়ননা দরখাস্ত তৌ',
    cancel: 'বাতিল তৌ',
    agree_terms: 'ঐহাক্না নিয়মশিং অসি য়ানিংই অমসুং পীরিবা মরোলশিং অসি অশেংবনি হায়না ফোংদোকচরি।',
    work_location: 'থবক শুফম মানচিত্র',
    route_details: 'লম্বী অমসুং অরাপ্পা',
    report_fraud: 'অরানবা থবক ওইরবদি খঙহনউ',
    checkout: 'দরখাস্ত নিশ্চিত তৌ',
    upload_images: 'মফম অদুগী ফোটো থাগৎউ',
    daily_wages: 'নুমিত খুদিংগী মজুরী',
    distance: 'অরাপ্পা',
    duration: 'মতাম',
    admin_dashboard: 'এদমিন ড্যাশবোর্ত',
    part_time_jobs: 'পার্ট টাইম থবক',
    apply_as_worker: 'থবক শুবা মীওই ওইনা দরখাস্ত তৌ',
    post_part_time_job: 'পার্ট টাইম থবক থাগৎউ',
    for_students_labourers: 'ছাত্র অমসুং থবক শুবা মীওইশিংগীদমক',
  },
  Nepali: {
    app_title: 'काममदत',
    powered_by: 'टीम ओरिजिन द्वारा संचालित',
    welcome: 'काममदतमा स्वागत छ',
    subtitle: 'भारतका कार्यबललाई जोड्दै।',
    i_am_worker: 'म एक श्रमिक हुँ',
    i_am_giver: 'म एक रोजगारदाता हुँ',
    admin_login: 'एडमिन लॉगिन',
    full_name: 'पूरा नाम',
    mobile_number: 'मोबाइल नम्बर',
    aadhar_number: 'आधार नम्बर',
    address: 'ठेगाना',
    email_id: 'इमेल आईडी',
    get_otp: 'ओटीपी प्राप्त गर्नुहोस्',
    verify_otp: 'ओटीपी सत्यापित गर्नुहोस्',
    enter_otp_sent_to: 'पठाइएको ओटीपी प्रविष्ट गर्नुहोस्',
    through: 'मार्फत',
    verify_and_login: 'सत्यापित र लॉगिन गर्नुहोस्',
    login_success: 'लॉगिन सफल भयो!',
    redirecting: 'तपाईको ड्यासबोर्डमा लादैछ...',
    applied_jobs: 'मैले आवेदन दिएको काम',
    posted_jobs: 'मैले पोष्ट गरेको काम',
    post_new_job: 'नयाँ काम पोष्ट गर्नुहोस्',
    search_jobs: 'काम खोज्नुहोस्',
    loyalty_card: 'लॉयल्टी कार्ड',
    jobs_in_india: 'सवै भारतभरि काम',
    salary: 'दैनिक तलब',
    location: 'स्थान',
    slots: 'खाली ठाउँ',
    apply_now: 'अहिले नै आवेदन दिनुहोस्',
    applied: 'आवेदन गरिएको',
    view_apply: 'हेर्नुहोस् र आवेदन दिनुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    agree_terms: 'म नियम र शर्तहरूमा सहमत छु र दिएको जानकारी सत्य हो भनी पुष्टि गर्दछु।',
    work_location: 'कामको स्थान नक्सा',
    route_details: 'बाटो र दूरी',
    report_fraud: 'नक्कली कामको रिपोर्ट गर्नुहोस्',
    checkout: 'आवेदन पक्का गर्नुहोस्',
    upload_images: 'स्थानको तस्विर अपलोड गर्नुहोस्',
    daily_wages: 'दैनिक ज्याला',
    distance: 'दूरी',
    duration: 'समय',
    admin_dashboard: 'एडमिन ड्यासबोर्ड',
    part_time_jobs: 'पार्ट टाइम काम',
    apply_as_worker: 'श्रमिकको रूपमा आवेदन दिनुहोस्',
    post_part_time_job: 'पार्ट टाइम काम पोष्ट गर्नुहोस्',
    for_students_labourers: 'विद्यार्थी र श्रमिकहरूको लागि',
  },
  Punjabi: {
    app_title: 'ਕਾਮਮਦਤ',
    powered_by: 'ਟੀਮ ਓਰਿਜਿਨ ਦੁਆਰਾ ਸੰਚਾਲਿਤ',
    welcome: 'ਕਾਮਮਦਤ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    subtitle: 'ਭਾਰਤ ਦੇ ਕਾਰਜਬਲ ਨੂੰ ਜੋੜਨਾ।',
    i_am_worker: 'ਮੈਂ ਇੱਕ ਕਾਮਾ ਹਾਂ',
    i_am_giver: 'ਮੈਂ ਇੱਕ ਰੁਜ਼ਗਾਰਦਾਤਾ ਹਾਂ',
    admin_login: 'ਐਡਮਿਨ ਲੌਗਇਨ',
    full_name: 'ਪੂਰਾ ਨਾਮ',
    mobile_number: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    aadhar_number: 'ਆਧਾਰ ਨੰਬਰ',
    address: 'ਪਤਾ',
    email_id: 'ਈਮੇਲ ਆਈਡੀ',
    get_otp: 'ਓਟੀਪੀ ਪ੍ਰਾਪਤ ਕਰੋ',
    verify_otp: 'ਓਟੀਪੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    enter_otp_sent_to: 'ਭੇਜਿਆ ਗਿਆ ਓਟੀਪੀ ਦਰਜ ਕਰੋ',
    through: 'ਰਾਹੀਂ',
    verify_and_login: 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ',
    login_success: 'ਲੌਗਇਨ ਸਫਲ ਰਿਹਾ!',
    redirecting: 'ਤੁਹਾਡੇ ਡੈਸ਼ਬੋਰਡ ਵੱਲ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    applied_jobs: 'ਮੇਰੇ ਅਪਲਾਈ ਕੀਤੇ ਕੰਮ',
    posted_jobs: 'ਮੇਰੇ ਪੋਸਟ ਕੀਤੇ ਕੰਮ',
    post_new_job: 'ਨਵਾਂ ਕੰਮ ਪੋਸਟ ਕਰੋ',
    search_jobs: 'ਕੰਮ ਲੱਭੋ',
    loyalty_card: 'ਲੌਇਲਟੀ ਕਾਰਡ',
    jobs_in_india: 'ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਨੌਕਰੀਆਂ',
    salary: 'ਰੋਜ਼ਾਨਾ ਤਨਖਾਹ',
    location: 'ਸਥਾਨ',
    slots: 'ਖਾਲੀ ਥਾਂਵਾਂ',
    apply_now: 'ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ',
    applied: 'ਅਪਲਾਈ ਕੀਤਾ ਗਿਆ',
    view_apply: 'ਦੇਖੋ ਅਤੇ ਅਪਲਾਈ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    agree_terms: 'ਮੈਂ ਨਿਯਮਾਂ ਅਤੇ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਹਾਂ ਅਤੇ ਪੁਸ਼ਟੀ ਕਰਦਾ ਹਾਂ ਕਿ ਸਾਰੇ ਵੇਰਵੇ ਸੱਚੇ ਹਨ।',
    work_location: 'ਕੰਮ ਵਾਲੀ ਥਾਂ ਦਾ ਨਕਸ਼ਾ',
    route_details: 'ਰਾਹ ਅਤੇ ਦੂਰੀ',
    report_fraud: 'ਫਰਜ਼ੀ ਕੰਮ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    checkout: 'ਅਪਲਾਈ ਪੱਕਾ ਕਰੋ',
    upload_images: 'ਕੰਮ ਵਾਲੀ ਥਾਂ ਦੀਆਂ ਤਸਵੀਰਾਂ ਅਪਲੋਡ ਕਰੋ',
    daily_wages: 'ਰੋਜ਼ਾਨਾ ਦਿਹਾੜੀ',
    distance: 'ਦੂਰੀ',
    duration: 'ਸਮਾਂ',
    admin_dashboard: 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',
    part_time_jobs: 'ਪਾਰਟ ਟਾਈਮ ਨੌਕਰੀਆਂ',
    apply_as_worker: 'ਕਾਮੇ ਵਜੋਂ ਅਪਲਾਈ ਕਰੋ',
    post_part_time_job: 'ਪਾਰਟ ਟਾਈਮ ਕੰਮ ਪੋਸਟ ਕਰੋ',
    for_students_labourers: 'ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਮਜ਼ਦੂਰਾਂ ਲਈ',
  },
  Urdu: {
    app_title: 'کام مدد',
    powered_by: 'ٹیم اوریجن کی جانب سے',
    welcome: 'کام مدد میں خوش آمدید',
    subtitle: 'بھارت کے محنت کشوں کو جوڑنا۔',
    i_am_worker: 'میں ایک مزدور ہوں',
    i_am_giver: 'میں ایک آجر ہوں',
    admin_login: 'ایڈمن لاگ ان',
    full_name: 'پورا نام',
    mobile_number: 'موبائل نمبر',
    aadhar_number: 'آدھار نمبر',
    address: 'پتہ',
    email_id: 'ای میل آئی ڈی',
    get_otp: 'او ٹی پی حاصل کریں',
    verify_otp: 'او ٹی پی کی تصدیق کریں',
    enter_otp_sent_to: 'بھیجا گیا او ٹی پی درج کریں',
    through: 'کے ذریعے',
    verify_and_login: 'تصدیق اور لاگ ان کریں',
    login_success: 'لاگ ان کامیاب رہا!',
    redirecting: 'ڈیش بورڈ پر منتقل کیا جا رہا ہے...',
    applied_jobs: 'کام جن کے لئے درخواست دی گئی',
    posted_jobs: 'میرے شائع کردہ کام',
    post_new_job: 'نیا کام شائع کریں',
    search_jobs: 'کام تلاش کریں',
    loyalty_card: 'لائلٹی کارڈ',
    jobs_in_india: 'پورے ہندوستان میں نوکریاں',
    salary: 'روزانہ اجرت',
    location: 'مقام',
    slots: 'نشستیں',
    apply_now: 'ابھی درخواست دیں',
    applied: 'درخواست دے دی گئی',
    view_apply: 'دیکھیں اور درخواست دیں',
    cancel: 'منسوخ کریں',
    agree_terms: 'میں تمام شرائط و ضوابط سے اتفاق کرتا ہوں اور تصدیق کرتا ہوں کہ معلومات درست ہیں۔',
    work_location: 'جائے وقوعہ کا نقشہ',
    route_details: 'راستہ اور فاصلہ',
    report_fraud: 'جعلی کام کی رپورٹ کریں',
    checkout: 'درخواست کی تصدیق کریں',
    upload_images: 'مقام کی تصاویر اپ لوڈ کریں',
    daily_wages: 'روزانہ اجرت',
    distance: 'فاصلہ',
    duration: 'وقت',
    admin_dashboard: 'ایڈمن ڈیش بورڈ',
    part_time_jobs: 'پارٹ ٹائم نوکریاں',
    apply_as_worker: 'بطور مزدور درخواست دیں',
    post_part_time_job: 'پارٹ ٹائم کام شائع کریں',
    for_students_labourers: 'طلباء اور مزدوروں کے لئے',
  },
  Assamese: {
    app_title: 'কামমদত',
    powered_by: 'টিম অৰিচিনৰ দ্বাৰা চালিত',
    welcome: 'কামমদতলৈ আদৰণি জনাইছোঁ',
    subtitle: 'ভাৰতৰ শ্ৰমশক্তি সংযোগ কৰা হৈছে।',
    i_am_worker: 'মই এজন কৰ্মী',
    i_am_giver: 'মই এজন নিয়োগকৰ্তা',
    admin_login: 'এডমিন লগইন',
    full_name: 'সম্পূৰ্ণ নাম',
    mobile_number: 'ম’বাইল নম্বৰ',
    aadhar_number: 'আধাৰ নম্বৰ',
    address: 'ঠিকনা',
    email_id: 'ইমেইল আইডি',
    get_otp: 'অ’টিপি লাভ কৰক',
    verify_otp: 'অ’টিপি পৰীক্ষা কৰক',
    enter_otp_sent_to: 'প্ৰেৰিত অ’টিপি লিখক',
    through: 'মাজেৰে',
    verify_and_login: 'পৰীক্ষা আৰু লগইন কৰক',
    login_success: 'লগইন সফল হৈছে!',
    redirecting: 'আপোনাৰ ডেশ্ববৰ্ডলৈ নিয়া হৈছে...',
    applied_jobs: 'মই আবেদন কৰা কাম',
    posted_jobs: 'মই পোষ্ট কৰা কাম',
    post_new_job: 'নতুন কাম পোষ্ট কৰক',
    search_jobs: 'কাম সন্ধান কৰক',
    loyalty_card: 'লয়্যালটি কাৰ্ড',
    jobs_in_india: 'গোটেই ভাৰতবৰ্ষতে কাম',
    salary: 'দৈনিক দৰমহা',
    location: 'স্থান',
    slots: 'খালী পদ',
    apply_now: 'এতিয়াই আবেদন কৰক',
    applied: 'আবেদন কৰা হৈছে',
    view_apply: 'চাওক আৰু আবেদন কৰক',
    cancel: 'বাতিল কৰক',
    agree_terms: 'মই নিয়ম আৰু চৰ্তাৱলীত সন্মত হৈছোঁ আৰু দিয়া তথ্য সত্য বুলি ঘোষণা কৰিছোঁ।',
    work_location: 'কৰ্মস্থানৰ মানচিত্ৰ',
    route_details: 'পথ আৰু দূৰত্ব',
    report_fraud: 'ভুৱা কামৰ ৰিপোৰ্ট কৰক',
    checkout: 'আবেদন নিশ্চিত কৰক',
    upload_images: 'ঠাইখনৰ ফটো আপলোড কৰক',
    daily_wages: 'দৈনিক হাজিৰা',
    distance: 'দূৰত্ব',
    duration: 'সময়',
    admin_dashboard: 'এডমিন ডেশ্ববৰ্ড',
    part_time_jobs: 'পাৰ্ট টাইম কাম',
    apply_as_worker: 'কৰ্মী হিচাপে আবেদন কৰক',
    post_part_time_job: 'পাৰ্ট টাইম কাম পোষ্ট কৰক',
    for_students_labourers: 'ছাত্ৰ আৰু বনুৱাসকলৰ বাবে',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('English');

  useEffect(() => {
    const savedLang = localStorage.getItem('kaammadat_lang') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('kaammadat_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['English']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
